### ISSUE TITLE
Light wont reset back to original color

### ISSUE THREAD

**Issue by Vaksky** [Jallah123/hue-ambiance#6] opened 2023-04-27 03:30 UTC
Hi I recreated the issue, not sure why its still happening for me.

https://streamable.com/rr9dpn

**Comment by Jallah123** [comment] 2023-05-04 13:49
Hi, I just tested it out and I can reproduce it. 

It seems like the hue library I'm using alerts for 15 seconds and then stops. After the 15 seconds it will stay the same color. It will actually go back to the original color once you fix the issue (e.g. not enough prayer or hp). 

I'm able to fix it but I can't give any timelines since I'm quite busy.

Thanks for reporting and I will fix it in the future.

**Comment by Vaksky** [comment] 2023-05-04 18:54
Thanks! Anything I can do on my end to fix the issue regarding settings until you get around to it?

Btw I absolutely love this plugin!

**Comment by Jallah123** [comment] 2023-05-04 19:56
There's nothing you can do atm to fix it. I think the only problem is that it stops blinking. For me it went back to the original color once I had enough hp/prayer. 

But let me know if there's something else wrong

**Comment by Jallah123** [comment] 2023-05-08 09:05
fixed in next version, it still needs to be merged in the plugin hub but that is out of my control

**Closed by Jallah123** 2023-05-08 09:05 UTC
